name: Weekly Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Runs at 00:00 UTC every Sunday
  push:
    branches: [ main ]
    paths-ignore:
      - '**'  # Ignore all paths to ensure it only triggers on schedule

jobs:
  weekly-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Cache Poetry virtualenv
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.1

      - name: Install dependencies
        run: poetry install --with dev

      - name: Run all tests
        run: poetry run pytest tests/
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}